export default {
  // https://github.com/fastify/fastify-accepts#readme
  accepts: 'fastify-accepts',
  // https://github.com/fastify/fastify-csrf#readme
  csrf: 'fastify-csrf',
  // https://github.com/fastify/fastify-cors#readme
  cors: 'fastify-cors',
  // https://github.com/fastify/fastify-cookie#readme
  cookie: 'fastify-cookie',
  // https://github.com/fastify/fastify-compress#readme
  compress: 'fastify-compress',
  // https://github.com/fastify/fastify-helmet#readme
  helmet: 'fastify-helmet',
  // https://github.com/fastify/fastify-jwt
  jwt: 'fastify-jwt',
  // https://github.com/fastify/fastify-static
  static: 'fastify-static',
  // https://github.com/fastify/fastify-postgres
  postgresql: 'fastify-postgres',
  // https://github.com/fastify/fastify-mongodb
  mongodb: 'fastify-mongodb',
  // https://github.com/fastify/point-of-view
  templates: 'point-of-view',
  // https://github.com/fastify/fastify-redis#readme
  redis: 'fastify-redis',
  // https://github.com/fastify/fastify-nextjs
  nextjs: 'fastify-nextjs',
  // https://github.com/smartiniOnGitHub/fastify-healthcheck
  health: 'fastify-healthcheck',
  // https://github.com/fastify/under-pressure
  pressure: 'under-pressure',
  // https://github.com/heply/fastify-bcrypt
  bcrypt: 'fastify-bcrypt',
}
